[package]
name = "peng-shop-backend-zypp"
version = "0.1.0"
authors = ["Imo Hester <vortex@z-ray.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.132"