[package]
name = "peng-shop-backend-zypp"
version = "0.1.0"
authors = ["Imo Hester <vortex@z-ray.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.75"

[buil-dependencies]
cxx-build = "1.0.75"